version: "3.8"

services:

  frontend:
    image: larsvandersangen/homebase-frontend:dev-latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    networks:
      - app-network
    expose:
      - "9000"
    entrypoint: ng serve --host 0.0.0.0 --poll 1

  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ${HOMEBASE_BACKEND_PROJECT_FOLDER}/public:/var/www/homebase-backend/public
      - ${HOMEBASE_BACKEND_PROJECT_FOLDER}/docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  phpfpm:
    image: larsvandersangen/homebase-backend:dev-latest
    platform: linux/amd64
    build:
      target: dev
      dockerfile: "${HOMEBASE_BACKEND_PROJECT_DOCKER_FILE}"
      context: "${HOMEBASE_BACKEND_PROJECT_FOLDER}"
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev

  redis:
    image: "redis:latest"

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
